### ISSUE TITLE
[BUG] Final Form finisher graphics are broken

### ISSUE THREAD

**Issue by tryashtar** [TopazTK/KH-ReFined#133] opened 2023-09-29 02:22 UTC
**Re:Fined Version:**
v4.00

**Game in Question:**
Kingdom Hearts II

**Bug Description:**
The graphics of Final Form Finishers are displayed incorrectly when using ReFined compared to vanilla.

**Reproduction Steps:**
1. Enter Final Form
2. Jump into the air
3. Do an air combo until the finisher

**Screenshots/Video:**
Vanilla finisher graphics (correct):
https://github.com/TopazTK/KH-ReFined/assets/26075577/af33a8dc-1133-408a-bf9a-6e6c8b5d2ffb
![image](https://github.com/TopazTK/KH-ReFined/assets/26075577/e813fbf1-358f-404e-9b54-d4b7ea1a3ef4)
![image](https://github.com/TopazTK/KH-ReFined/assets/26075577/201e6324-8390-4b80-b59a-f5ff75aaf5f3)

ReFined finisher graphics (incorrect):
https://github.com/TopazTK/KH-ReFined/assets/26075577/fbe022f8-1152-4c05-9f44-462548c87ba3
![image](https://github.com/TopazTK/KH-ReFined/assets/26075577/0c784620-e39e-4811-90cb-bc888fdb9e85)
![image](https://github.com/TopazTK/KH-ReFined/assets/26075577/b87009df-4115-44cc-ba1f-0cd55cefb913)

**Comment by TopazTK** [comment] 2023-09-29 21:03
Seems to be caused by the Mod Manager. This is an OpenKH bug, please report to: https://github.com/OpenKH/OpenKh
Closing as it isn't a Re:Fined issue within itself.

**Closed by TopazTK** 2023-09-29 21:03 UTC
Labels: Bug
