### ISSUE TITLE
[BUG] Menu sounds get cut off in certain menus

### ISSUE THREAD

**Issue by tryashtar** [TopazTK/KH-ReFined#134] opened 2023-09-29 02:30 UTC
**Re:Fined Version:**
v4.00

**Game in Question:**
Kingdom Hearts II

**Bug Description:**
In certain menus (e.g. the continue screen), the menu select sounds do not play properly.

**Reproduction Steps:**
1. Enter a fight
2. Die
3. Navigate the options and listen

**Screenshots/Video:**
https://github.com/TopazTK/KH-ReFined/assets/26075577/c292641e-8622-4fae-a3ea-3965264b77a4

**Comment by TopazTK** [comment] 2023-09-29 21:01
Not fixable due to the game itself causing this issue.
Closing as "not completed".

**Closed by TopazTK** 2023-09-29 21:01 UTC
Labels: Bug

**Comment by tryashtar** [comment] 2023-09-29 22:18
It's not an issue in vanilla

**Comment by TopazTK** [comment] 2023-09-30 00:59
Yea but Vanilla doesn't fuck with the game to this degree. I will look into it, but I am not doing anything to cause this, furthermore, I cannot reproduce this at all.
